name: Agentic QA CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Agentic QA Workflow
    runs-on: macos-latest  # or ubuntu-latest if you're using headless setup

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PDM
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Project Dependencies
        run: pdm install

      - name: Install Playwright Browsers
        run: pdm run python -m playwright install

      - name: Run Linter
        run: pdm run ruff check .

      - name: Run Agents
        run: pdm run python main.py

      - name: Run Tests
        run: pdm run pytest
